### ISSUE TITLE
SocketTimeoutException on entering dashboard

### ISSUE THREAD

**Issue by vikipedia48** [web3labs/chainlens-free#74]
When entering the Chainlens dashboard, an error occurs: 

ingestion_1  | 2024-03-27T08:49:14.988Z ERROR 1 --- [pool-9-thread-1] i.e.e.i.b.workers.BlockDispatcherRunner  : Connect timed out
ingestion_1  | 
ingestion_1  | java.net.SocketTimeoutException: Connect timed out
ingestion_1  | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[na:na]
ingestion_1  | 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[na:na]
ingestion_1  | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
ingestion_1  | 	at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
ingestion_1  | 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:246) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.connection.ConnectPlan.connectTcp(ConnectPlan.kt:128) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.connection.SequentialExchangeFinder.find(SequentialExchangeFinder.kt:33) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:267) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at io.epirus.explorer.config.BasicHttpService$Companion$createClient$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1152) ~[config-3.3.10.jar!/:na]
ingestion_1  | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158) ~[okhttp-jvm-5.0.0-alpha.7.jar!/:na]
ingestion_1  | 	at org.web3j.protocol.http.HttpService.performIO(HttpService.java:159) ~[core-4.10.2.jar!/:na]
ingestion_1  | 	at org.web3j.protocol.Service.send(Service.java:48) ~[core-4.10.2.jar!/:na]
ingestion_1  | 	at org.web3j.protocol.core.Request.send(Request.java:87) ~[core-4.10.2.jar!/:na]
ingestion_1  | 	at io.epirus.explorer.ingestion.blocks.BlockHeightExtractor.ingestBlockNumberIfReady(BlockHeightExtractor.kt:50) ~[classes!/:3.3.10]
ingestion_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
ingestion_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
ingestion_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
ingestion_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
ingestion_1  | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at io.micrometer.core.aop.TimedAspect.processWithTimer(TimedAspect.java:227) ~[micrometer-core-1.12.3.jar!/:1.12.3]
ingestion_1  | 	at io.micrometer.core.aop.TimedAspect.perform(TimedAspect.java:202) ~[micrometer-core-1.12.3.jar!/:1.12.3]
ingestion_1  | 	at io.micrometer.core.aop.TimedAspect.timedMethod(TimedAspect.java:194) ~[micrometer-core-1.12.3.jar!/:1.12.3]
ingestion_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
ingestion_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
ingestion_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
ingestion_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
ingestion_1  | 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) ~[spring-aop-6.0.13.jar!/:6.0.13]
ingestion_1  | 	at io.epirus.explorer.ingestion.blocks.BlockHeightExtractor$$SpringCGLIB$$0.ingestBlockNumberIfReady(<generated>) ~[classes!/:3.3.10]
ingestion_1  | 	at io.epirus.explorer.ingestion.blocks.BlockHeightDispatcher.tick(BlockHeightDispatcher.kt:30) ~[classes!/:3.3.10]
ingestion_1  | 	at io.epirus.explorer.ingestion.blocks.workers.BlockDispatcherRunner.run(BlockDispatcherRunner.kt:16) ~[classes!/:3.3.10]
ingestion_1  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
ingestion_1  | 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
ingestion_1  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
ingestion_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
ingestion_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
ingestion_1  | 	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
ingestion_1  | 

My guess is it would be connected to the WS_API_URL property in the docker-compose (web image section). I don't think it's my connection to the RPC node, because when I had done this before and set an invalid RPC address, I got a different error (ConnectException or something similar). 

As it is, I have set web image's params to : 
    environment:
      - API_URL=/api
      - WS_API_URL=http://host.docker.internal:8090
      - DISPLAY_NETWORK_TAB=disabled

However, I based that only on the example docker-compose file (port 8090). Even if my error is unrelated to it, some clarification could be given for what does WS_API_URL do.

**Comment by haerker** [comment]
I also encountered the same error, ingestion_1 connection timed out, but it was running normally two days ago. I need help.

**Comment by vikipedia48** [comment]
In case you're wondering, it does not throw the exception (and works fine) when connecting to a quorum-dev-quickstart container hosted on the same computer (quorum-dev-quickstart already contains a quicklens image, but I disabled it to test whether hosting chainlens independently works). It does throw it when I connect to a remote RPC node. Again, what is WS_API_URL supposed to mean? Is it likely connected to the SocketTimeoutException?

**Comment by haerker** [comment]
you can try change docker-compose.yml web sections environment "- WS_API_URL=http://localhost:8090/" to "- WS_API_URL=ws://localhost:8090" and try again

**Comment by vikipedia48** [comment]
I did and still throws. - WS_API_URL=ws://host.docker.internal:8090 likewise throws.

**Comment by vikipedia48** [comment]
The error was with our server. The Websocket port was not set up properly. 
That being said, for anyone who wonders about WS_API_URL in the future, it's supposed to connect to the Websocket port of the RPC node (e.g. ws://127.0.0.1:8546), which must be set up.

**Comment by haerker** [comment]
hi @vikipedia48 
I'm having this problem again, can you tell me how you solved it in the first place, the more details the better, thanks!

**Comment by vikipedia48** [comment]
It was a problem with our server. The WS port wasn't yet configured by the team that manages it.
